import isaaclab.sim as sim_utils
from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets import ArticulationCfg


SMPLX_CFG = ArticulationCfg(
    spawn=sim_utils.UsdFileCfg(
        usd_path="protomotions/data/assets/usd/smplx_humanoid.usda",
        activate_contact_sensors=True,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            retain_accelerations=False,
            linear_damping=0.0,
            angular_damping=0.0,
            max_linear_velocity=1000.0,
            max_angular_velocity=1000.0,
            max_depenetration_velocity=1.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=True,
            solver_position_iteration_count=4,
            solver_velocity_iteration_count=4,
        ),
        visual_material=sim_utils.PreviewSurfaceCfg(
            diffuse_color=(0.65, 0.1, 1.0), metallic=0.5
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, 0.95),
        joint_pos={".*": 0.0},
        joint_vel={".*": 0.0},
    ),
    soft_joint_pos_limit_factor=0.9,
    actuators={
        "legs": ImplicitActuatorCfg(
            joint_names_expr=[
                "L_Hip_.",
                "R_Hip_.",
                "L_Knee_.",
                "R_Knee_.",
                "L_Ankle_.",
                "R_Ankle_.",
                "L_Toe_.",
                "R_Toe_.",
            ],
            effort_limit=500,
            velocity_limit=100.0,
            stiffness={
                "L_Hip_.": 800,
                "R_Hip_.": 800,
                "L_Knee_.": 800,
                "R_Knee_.": 800,
                "L_Ankle_.": 800,
                "R_Ankle_.": 800,
                "L_Toe_.": 500,
                "R_Toe_.": 500,
            },
            damping={
                "L_Hip_.": 80,
                "R_Hip_.": 80,
                "L_Knee_.": 80,
                "R_Knee_.": 80,
                "L_Ankle_.": 80,
                "R_Ankle_.": 80,
                "L_Toe_.": 50,
                "R_Toe_.": 50,
            },
        ),
        "torso": ImplicitActuatorCfg(
            joint_names_expr=[
                "Torso_.",
                "Spine_.",
                "Chest_.",
                "Neck_.",
                "Head_.",
                "L_Thorax_.",
                "R_Thorax_.",
            ],
            effort_limit=500,
            velocity_limit=100.0,
            stiffness={
                "Torso_.": 1000,
                "Spine_.": 1000,
                "Chest_.": 1000,
                "Neck_.": 500,
                "Head_.": 500,
                "L_Thorax_.": 500,
                "R_Thorax_.": 500,
            },
            damping={
                "Torso_.": 100,
                "Spine_.": 100,
                "Chest_.": 100,
                "Neck_.": 50,
                "Head_.": 50,
                "L_Thorax_.": 50,
                "R_Thorax_.": 50,
            },
        ),
        "arms": ImplicitActuatorCfg(
            joint_names_expr=[
                "L_Shoulder_.",
                "R_Shoulder_.",
                "L_Elbow_.",
                "R_Elbow_.",
                "L_Wrist_.",
                "R_Wrist_.",
            ],
            effort_limit=300,
            velocity_limit=100.0,
            stiffness={
                "L_Shoulder_.": 500,
                "R_Shoulder_.": 500,
                "L_Elbow_.": 300,
                "R_Elbow_.": 300,
                "L_Wrist_.": 300,
                "R_Wrist_.": 300,
            },
            damping={
                "L_Shoulder_.": 50,
                "R_Shoulder_.": 50,
                "L_Elbow_.": 30,
                "R_Elbow_.": 30,
                "L_Wrist_.": 30,
                "R_Wrist_.": 30,
            },
        ),
        "hands": ImplicitActuatorCfg(
            joint_names_expr=[
                "L_Index1_.",
                "L_Index2_.",
                "L_Index3_.",
                "L_Middle1_.",
                "L_Middle2_.",
                "L_Middle3_.",
                "L_Pinky1_.",
                "L_Pinky2_.",
                "L_Pinky3_.",
                "L_Ring1_.",
                "L_Ring2_.",
                "L_Ring3_.",
                "L_Thumb1_.",
                "L_Thumb2_.",
                "L_Thumb3_.",
                "R_Index1_.",
                "R_Index2_.",
                "R_Index3_.",
                "R_Middle1_.",
                "R_Middle2_.",
                "R_Middle3_.",
                "R_Pinky1_.",
                "R_Pinky2_.",
                "R_Pinky3_.",
                "R_Ring1_.",
                "R_Ring2_.",
                "R_Ring3_.",
                "R_Thumb1_.",
                "R_Thumb2_.",
                "R_Thumb3_.",
            ],
            effort_limit=5,
            velocity_limit=5.0,
            stiffness={
                "L_Index1_.": 10,
                "L_Index2_.": 10,
                "L_Index3_.": 10,
                "L_Middle1_.": 10,
                "L_Middle2_.": 10,
                "L_Middle3_.": 10,
                "L_Pinky1_.": 10,
                "L_Pinky2_.": 10,
                "L_Pinky3_.": 10,
                "L_Ring1_.": 10,
                "L_Ring2_.": 10,
                "L_Ring3_.": 10,
                "L_Thumb1_.": 10,
                "L_Thumb2_.": 10,
                "L_Thumb3_.": 10,
                "R_Index1_.": 10,
                "R_Index2_.": 10,
                "R_Index3_.": 10,
                "R_Middle1_.": 10,
                "R_Middle2_.": 10,
                "R_Middle3_.": 10,
                "R_Pinky1_.": 10,
                "R_Pinky2_.": 10,
                "R_Pinky3_.": 10,
                "R_Ring1_.": 10,
                "R_Ring2_.": 10,
                "R_Ring3_.": 10,
                "R_Thumb1_.": 10,
                "R_Thumb2_.": 10,
                "R_Thumb3_.": 10,
            },
            damping={
                "L_Index1_.": 1,
                "L_Index3_.": 1,
                "L_Middle1_.": 1,
                "L_Middle3_.": 1,
                "L_Pinky1_.": 1,
                "L_Pinky3_.": 1,
                "L_Ring1_.": 1,
                "L_Ring3_.": 1,
                "L_Thumb1_.": 1,
                "L_Thumb3_.": 1,
                "R_Index1_.": 1,
                "R_Index3_.": 1,
                "R_Middle1_.": 1,
                "R_Middle3_.": 1,
                "R_Pinky1_.": 1,
                "R_Pinky3_.": 1,
                "R_Ring1_.": 1,
                "R_Ring3_.": 1,
                "R_Thumb1_.": 1,
                "R_Thumb3_.": 1,
            },
        ),
    },
)


SMPL_CFG = ArticulationCfg(
    spawn=sim_utils.UsdFileCfg(
        usd_path="protomotions/data/assets/usd/smpl_humanoid.usda",
        activate_contact_sensors=True,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            retain_accelerations=False,
            linear_damping=0.0,
            angular_damping=0.0,
            max_linear_velocity=1000.0,
            max_angular_velocity=1000.0,
            max_depenetration_velocity=1.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=True,
            solver_position_iteration_count=4,
            solver_velocity_iteration_count=4,
        ),
        visual_material=sim_utils.PreviewSurfaceCfg(
            diffuse_color=(0.65, 0.1, 1.0), metallic=0.5
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(
            0.0,
            0.0,
            0.95,
        ),  # Default initial state of SMPL with the upright configuration
        joint_pos={".*": 0.0},
        joint_vel={".*": 0.0},
    ),
    soft_joint_pos_limit_factor=0.9,
    actuators={
        "legs": ImplicitActuatorCfg(
            joint_names_expr=[
                "L_Hip_.",
                "R_Hip_.",
                "L_Knee_.",
                "R_Knee_.",
                "L_Ankle_.",
                "R_Ankle_.",
                "L_Toe_.",
                "R_Toe_.",
            ],
            effort_limit=500,
            velocity_limit=100.0,
            stiffness={
                "L_Hip_.": 800,
                "R_Hip_.": 800,
                "L_Knee_.": 800,
                "R_Knee_.": 800,
                "L_Ankle_.": 800,
                "R_Ankle_.": 800,
                "L_Toe_.": 500,
                "R_Toe_.": 500,
            },
            damping={
                "L_Hip_.": 80,
                "R_Hip_.": 80,
                "L_Knee_.": 80,
                "R_Knee_.": 80,
                "L_Ankle_.": 80,
                "R_Ankle_.": 80,
                "L_Toe_.": 50,
                "R_Toe_.": 50,
            },
        ),
        "torso": ImplicitActuatorCfg(
            joint_names_expr=[
                "Torso_.",
                "Spine_.",
                "Chest_.",
                "Neck_.",
                "Head_.",
                "L_Thorax_.",
                "R_Thorax_.",
            ],
            effort_limit=500,
            velocity_limit=100.0,
            stiffness={
                "Torso_.": 1000,
                "Spine_.": 1000,
                "Chest_.": 1000,
                "Neck_.": 500,
                "Head_.": 500,
                "L_Thorax_.": 500,
                "R_Thorax_.": 500,
            },
            damping={
                "Torso_.": 100,
                "Spine_.": 100,
                "Chest_.": 100,
                "Neck_.": 50,
                "Head_.": 50,
                "L_Thorax_.": 50,
                "R_Thorax_.": 50,
            },
        ),
        "arms": ImplicitActuatorCfg(
            joint_names_expr=[
                "L_Shoulder_.",
                "R_Shoulder_.",
                "L_Elbow_.",
                "R_Elbow_.",
                "L_Wrist_.",
                "R_Wrist_.",
                "L_Hand_.",
                "R_Hand_.",
            ],
            effort_limit=500,
            velocity_limit=100.0,
            stiffness={
                "L_Shoulder_.": 500,
                "R_Shoulder_.": 500,
                "L_Elbow_.": 500,
                "R_Elbow_.": 500,
                "L_Wrist_.": 300,
                "R_Wrist_.": 300,
                "L_Hand_.": 300,
                "R_Hand_.": 300,
            },
            damping={
                "L_Shoulder_.": 50,
                "R_Shoulder_.": 50,
                "L_Elbow_.": 50,
                "R_Elbow_.": 50,
                "L_Wrist_.": 30,
                "R_Wrist_.": 30,
            },
        ),
    },
)


BIO_CFG = ArticulationCfg(
    spawn=sim_utils.UsdFileCfg(
        usd_path="protomotions/data/assets/usd/bio.usda",
        activate_contact_sensors=True,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            retain_accelerations=False,
            linear_damping=0.0,
            angular_damping=0.0,
            max_linear_velocity=1000.0,
            max_angular_velocity=1000.0,
            max_depenetration_velocity=1.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=False,
            solver_position_iteration_count=4,
            solver_velocity_iteration_count=4,
        ),
        visual_material=sim_utils.PreviewSurfaceCfg(
            diffuse_color=(0.65, 0.1, 1.0), metallic=0.5
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(
            0.0,
            0.0,
            0.95,
        ),  # Default initial state of SMPL with the upright configuration
        joint_pos={".*": 0.0},
        joint_vel={".*": 0.0},
    ),
    soft_joint_pos_limit_factor=0.9,
    actuators={
        "legs": ImplicitActuatorCfg(
            joint_names_expr=[
                "L_Hip_.",
                "R_Hip_.",
                "L_Knee",
                "R_Knee",
                "L_Ankle_.",
                "R_Ankle_.",
                "L_ToeThumb",
                "L_ToePinky",
                "R_ToeThumb",
                "R_ToePinky",
            ],
            effort_limit=500,
            velocity_limit=100.0,
            stiffness={
                "L_Hip_.": 400,
                "R_Hip_.": 400,
                "L_Knee": 300,
                "R_Knee": 300,
                "L_Ankle_.": 400,
                "R_Ankle_.": 400,
                "L_ToeThumb": 40,
                "L_ToePinky": 40,
                "R_ToeThumb": 40,
                "R_ToePinky": 40,
            },
            damping={
                "L_Hip_.": 6.0,
                "R_Hip_.": 6.0,
                "L_Knee": 4.5,
                "R_Knee": 4.5,
                "L_Ankle_.": 6.0,
                "R_Ankle_.": 6.0,
                "L_ToeThumb": 0.6,
                "L_ToePinky": 0.6,
                "R_ToeThumb": 0.6,
                "R_ToePinky": 0.6,
            },
        ),
        "torso": ImplicitActuatorCfg(
            joint_names_expr=[
                "Torso_.",
                "Spine_.",
                "Neck_.",
                "Head_.",
            ],
            effort_limit=500,
            velocity_limit=100.0,
            stiffness={
                "Torso_.": 500,
                "Spine_.": 300,
                "Neck_.": 60,
                "Head_.": 60,
            },
            damping={
                "Torso_.": 7.5,
                "Spine_.": 4.5,
                "Neck_.": 0.9,
                "Head_.": 0.9,
            },
        ),
        "arms": ImplicitActuatorCfg(
            joint_names_expr=[
                "L_Shoulder_.",
                "R_Shoulder_.",
                "L_Elbow_.",
                "R_Elbow_.",
                "ForeArmL_.",
                "ForeArmR_.",
                "HandL_.",
                "HandR_.",
            ],
            effort_limit=500,
            velocity_limit=100.0,
            stiffness={
                "L_Shoulder_.": 200,
                "R_Shoulder_.": 200,
                "L_Elbow_.": 150,
                "R_Elbow_.": 150,
                "ForeArmL_.": 80,
                "ForeArmR_.": 80,
                "HandL_.": 50,
                "HandR_.": 50,
            },
            damping={
                "L_Shoulder_.": 3.0,
                "R_Shoulder_.": 3.0,
                "L_Elbow_.": 2.25,
                "R_Elbow_.": 2.25,
                "ForeArmL_.": 1.2,
                "ForeArmR_.": 1.2,
                "HandL_.": 0.75,
                "HandR_.": 0.75,
            },
        ),
    },
)


H1_CFG = ArticulationCfg(
    spawn=sim_utils.UsdFileCfg(
        usd_path="protomotions/data/assets/usd/h1.usd",
        activate_contact_sensors=True,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            retain_accelerations=False,
            linear_damping=0.0,
            angular_damping=0.0,
            max_linear_velocity=1000.0,
            max_angular_velocity=1000.0,
            max_depenetration_velocity=1.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=False,
            solver_position_iteration_count=4,
            solver_velocity_iteration_count=4,
        ),
    ),
    soft_joint_pos_limit_factor=0.9,
)


BIO_ACT_CFG = ArticulationCfg(
    spawn=sim_utils.UsdFileCfg(
        usd_path="protomotions/data/assets/usd/bio.usda",
        activate_contact_sensors=True,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            retain_accelerations=False,
            linear_damping=0.0,
            angular_damping=0.0,
            max_linear_velocity=1000.0,
            max_angular_velocity=1000.0,
            max_depenetration_velocity=1.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=False,
            solver_position_iteration_count=4,
            solver_velocity_iteration_count=4,
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, 0.95),
        joint_pos={".*": 0.0},
        joint_vel={".*": 0.0},
    ),
    soft_joint_pos_limit_factor=0.9,
    actuators={},
)


G1_CFG = ArticulationCfg(
    spawn=sim_utils.UsdFileCfg(
        usd_path="protomotions/data/assets/usd/g1.usd",
        activate_contact_sensors=True,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            retain_accelerations=False,
            linear_damping=0.0,
            angular_damping=0.0,
            max_linear_velocity=1000.0,
            max_angular_velocity=1000.0,
            max_depenetration_velocity=1.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=False,
            solver_position_iteration_count=4,
            solver_velocity_iteration_count=4,
        ),
    ),
    soft_joint_pos_limit_factor=0.9,
)
